### ISSUE TITLE
Unit testable code

### ISSUE THREAD

**Issue by wj-0816** [soonevel/TechCreate#8]
https://github.com/soonevel/TechCreate/blob/2783d994e72e15698ca86fe7b1eed7ea5aea3d27/src/main/java/org/example/Generator.java#L51-L58

Current unit test case is testing against the throwable error. However, this section of code is unit testable too. We can convert this section to a function and write a test function for it.

**Comment by wj-0816** [comment]
Changes for this issue please commit into separate branch and submit it as pull request (PR).

**Comment by soonevel** [comment]
Created `splitLine` function, and added a few `splitLine_*` test cases in `GeneratorTest` to test it. Please let me know if more test cases are needed, thanks.

PR link: https://github.com/soonevel/TechCreate/pull/9

**Comment by wj-0816** [comment]
What are the advantages of Pull Requests(PR) over direct commits to the `main` branch?

**Comment by soonevel** [comment]
I would say first of all, PR protects the `main` branch, which is supposed to be working at all times, from breaking due to any changes. PR is usually reviewed by others to ensure that any concerns are raised and addressed before merging the changes into the `main` branch, which is typically used in production. Additionally, if implemented, CI/CD pipelines can be triggered automatically for each PR before the changes are merged into the `main` branch, acting as a safety barrier. People can work on different parts of the same project simultaneously on different branches, with each PR containing changes for a feature, sub-feature, or specific task. This greatly improves the organization and structure of the code, making it easier to navigate and troubleshoot issues that may arise after changes are merged, while minimizing interference with others' changes during development. One downside is resolving merge conflicts, which can be tedious. However, at times when the changes for a particular task should be removed, it is much easier to abandon or revert changes from a PR than to unwind them from a series of mixed commits.

**Comment by wj-0816** [comment]
One way to prevent from merge conflicts would be try to rebase/merge your code from `main`/parent branch as frequent as possible and try to close PR asap.
